# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:
    branches: [ master, develope ]


jobs:
  deploy:

    runs-on: raspi

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Create .env file
      # You may pin to the exact commit or the version.
      # uses: SpicyPizza/create-envfile@68bc962e171da964dea0d34ca817dd5f246a8f53
      uses: SpicyPizza/create-envfile@v1.0
      with:

        envkey_DBPATH:  ${{ secrets.DBPATH }}
        envkey_OLDDBPATH:  ${{ secrets.OLDDBPATH }}
        envkey_TOKEN: ${{ secrets.TOKEN }}
        envkey_prefix: f!
        
        envkey_IGNITEAPI: ${{ secrets.IGNITEAPI }}
        envkey_CAT_TOKEN: ${{ secrets.CAT_TOKEN }}
        envkey_HYPIXELTOKEN: ${{ secrets.HYPIXELTOKEN }}
        envkey_SENTRY: ${{ secrets.SENTRY }}
        envkey_ENV: Production


    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart FishyBot
    
